export const mockClients = [
  {
    id: 1,
    nombre: "Arni McClifferty",
    correo: "amcclifferty0@blogs.com",
    telefono: "735-218-6443",
    direccion: "9218 Eagan Crossing",
  },
  {
    id: 2,
    nombre: "Mollie Basini-Gazzi",
    correo: "mbasinigazzi1@vinaora.com",
    telefono: "519-526-8137",
    direccion: "8 Bashford Trail",
  },
  {
    id: 3,
    nombre: "Pete Speek",
    correo: "pspeek2@google.pl",
    telefono: "493-879-8737",
    direccion: "8 Pleasure Point",
  },
  {
    id: 4,
    nombre: "Sol Bottlestone",
    correo: "sbottlestone3@cpanel.net",
    telefono: "490-440-5770",
    direccion: "883 Schiller Place",
  },
  {
    id: 5,
    nombre: "Valentijn Klemensiewicz",
    correo: "vklemensiewicz4@ted.com",
    telefono: "392-104-8327",
    direccion: "3 Spaight Park",
  },
  {
    id: 6,
    nombre: "Maryjo Notman",
    correo: "mnotman5@google.ca",
    telefono: "868-434-1116",
    direccion: "85084 Becker Court",
  },
  {
    id: 7,
    nombre: "Heriberto Farragher",
    correo: "hfarragher6@edublogs.org",
    telefono: "406-323-6923",
    direccion: "8527 Red Cloud Plaza",
  },
  {
    id: 8,
    nombre: "Tisha Pryce",
    correo: "tpryce7@freewebs.com",
    telefono: "241-239-1423",
    direccion: "7 Pankratz Way",
  },
  {
    id: 9,
    nombre: "Jeniffer Print",
    correo: "jprint8@nationalgeographic.com",
    telefono: "602-223-0692",
    direccion: "67815 Sundown Place",
  },
  {
    id: 10,
    nombre: "Millisent Brodeau",
    correo: "mbrodeau9@microsoft.com",
    telefono: "337-276-9460",
    direccion: "6521 Del Mar Hill",
  },
  {
    id: 11,
    nombre: "Nana Drayton",
    correo: "ndraytona@bandcamp.com",
    telefono: "661-555-4204",
    direccion: "0 Glendale Trail",
  },
  {
    id: 12,
    nombre: "Guinna Hammerstone",
    correo: "ghammerstoneb@biglobe.ne.jp",
    telefono: "582-735-2316",
    direccion: "63 Eagan Circle",
  },
  {
    id: 13,
    nombre: "Cherish Mould",
    correo: "cmouldc@rambler.ru",
    telefono: "273-991-6995",
    direccion: "592 Rutledge Drive",
  },
  {
    id: 14,
    nombre: "Anton Townby",
    correo: "atownbyd@ox.ac.uk",
    telefono: "785-965-4764",
    direccion: "7930 Corry Crossing",
  },
  {
    id: 15,
    nombre: "Rubi Panks",
    correo: "rpankse@springer.com",
    telefono: "200-482-8138",
    direccion: "08 Oxford Park",
  },
  {
    id: 16,
    nombre: "Edna Oakland",
    correo: "eoaklandf@miitbeian.gov.cn",
    telefono: "818-784-4841",
    direccion: "465 Truax Plaza",
  },
  {
    id: 17,
    nombre: "Frannie Nardrup",
    correo: "fnardrupg@meetup.com",
    telefono: "884-825-9831",
    direccion: "21989 Hagan Crossing",
  },
  {
    id: 18,
    nombre: "George Haestier",
    correo: "ghaestierh@altervista.org",
    telefono: "173-578-5395",
    direccion: "6 Lindbergh Parkway",
  },
  {
    id: 19,
    nombre: "Zitella Matusovsky",
    correo: "zmatusovskyi@gov.uk",
    telefono: "355-690-1943",
    direccion: "24600 Bay Trail",
  },
  {
    id: 20,
    nombre: "Omar Patrono",
    correo: "opatronoj@comcast.net",
    telefono: "441-989-0682",
    direccion: "8 Merrick Street",
  },
  {
    id: 21,
    nombre: "Jackelyn Keener",
    correo: "jkeenerk@hexun.com",
    telefono: "184-502-1744",
    direccion: "2881 Orin Junction",
  },
  {
    id: 22,
    nombre: "Niven Rubinowitch",
    correo: "nrubinowitchl@usa.gov",
    telefono: "130-583-3725",
    direccion: "6889 Surrey Trail",
  },
  {
    id: 23,
    nombre: "Innis Ellice",
    correo: "iellicem@census.gov",
    telefono: "961-772-7749",
    direccion: "20646 Farwell Crossing",
  },
  {
    id: 24,
    nombre: "Jamal Montrose",
    correo: "jmontrosen@dailymotion.com",
    telefono: "603-453-5533",
    direccion: "68992 Havey Street",
  },
  {
    id: 25,
    nombre: "Ramsay Keyworth",
    correo: "rkeywortho@geocities.jp",
    telefono: "604-257-1194",
    direccion: "4343 Montana Street",
  },
  {
    id: 26,
    nombre: "Ernst Bache",
    correo: "ebachep@springer.com",
    telefono: "303-829-3280",
    direccion: "12785 Roth Alley",
  },
  {
    id: 27,
    nombre: "Daveta Filan",
    correo: "dfilanq@blogs.com",
    telefono: "271-542-7604",
    direccion: "43 Mariners Cove Avenue",
  },
  {
    id: 28,
    nombre: "Paulita Haversham",
    correo: "phavershamr@homestead.com",
    telefono: "664-425-9843",
    direccion: "81 Gulseth Trail",
  },
  {
    id: 29,
    nombre: "Ingamar Plews",
    correo: "iplewss@jiathis.com",
    telefono: "345-813-3796",
    direccion: "0982 Delaware Street",
  },
  {
    id: 30,
    nombre: "Caresse Martell",
    correo: "cmartellt@wiley.com",
    telefono: "510-353-6870",
    direccion: "471 Garrison Point",
  },
  {
    id: 31,
    nombre: "Hobart Catherick",
    correo: "hcathericku@altervista.org",
    telefono: "464-313-8197",
    direccion: "7 Springview Plaza",
  },
  {
    id: 32,
    nombre: "Rici McNickle",
    correo: "rmcnicklev@biblegateway.com",
    telefono: "164-961-0386",
    direccion: "31 6th Crossing",
  },
  {
    id: 33,
    nombre: "Carley Joisce",
    correo: "cjoiscew@wikipedia.org",
    telefono: "747-680-1812",
    direccion: "662 Kenwood Terrace",
  },
  {
    id: 34,
    nombre: "Astrix Tranter",
    correo: "atranterx@unesco.org",
    telefono: "684-361-6491",
    direccion: "41 Morningstar Terrace",
  },
  {
    id: 35,
    nombre: "Selby Gudgion",
    correo: "sgudgiony@myspace.com",
    telefono: "394-479-7997",
    direccion: "113 Holmberg Park",
  },
  {
    id: 36,
    nombre: "Orin Egglestone",
    correo: "oegglestonez@qq.com",
    telefono: "459-330-5521",
    direccion: "1338 Kedzie Terrace",
  },
  {
    id: 37,
    nombre: "Randi Halbard",
    correo: "rhalbard10@auda.org.au",
    telefono: "700-180-1541",
    direccion: "44316 Pepper Wood Street",
  },
  {
    id: 38,
    nombre: "Kathi Edgley",
    correo: "kedgley11@comcast.net",
    telefono: "629-340-1640",
    direccion: "64321 Bay Crossing",
  },
  {
    id: 39,
    nombre: "Henryetta Mar",
    correo: "hmar12@about.me",
    telefono: "919-555-2422",
    direccion: "4968 Carberry Junction",
  },
  {
    id: 40,
    nombre: "Gianina Gurrado",
    correo: "ggurrado13@lulu.com",
    telefono: "351-974-7606",
    direccion: "4 Jenna Lane",
  },
  {
    id: 41,
    nombre: "Yank Maymand",
    correo: "ymaymand14@virginia.edu",
    telefono: "543-155-3941",
    direccion: "20 Forest Dale Crossing",
  },
  {
    id: 42,
    nombre: "Charo Sparks",
    correo: "csparks15@npr.org",
    telefono: "466-925-3470",
    direccion: "6116 Westridge Alley",
  },
  {
    id: 43,
    nombre: "Klemens Rivalland",
    correo: "krivalland16@people.com.cn",
    telefono: "113-162-9862",
    direccion: "44 Comanche Parkway",
  },
  {
    id: 44,
    nombre: "Perrine Worgan",
    correo: "pworgan17@ehow.com",
    telefono: "721-308-5938",
    direccion: "5 Victoria Drive",
  },
  {
    id: 45,
    nombre: "Scottie Brezlaw",
    correo: "sbrezlaw18@apache.org",
    telefono: "249-332-9373",
    direccion: "5138 Kingsford Court",
  },
];
