export const mockProductos = [
  {
    id: 1,
    nombre: "Kids' Science Experiment Kit",
    descripcion: "Engaging kit with science experiments for children.",
    precio: 29.99,
    stock: 6002,
  },
  {
    id: 2,
    nombre: "Electric Toothbrush",
    descripcion: "Rechargeable electric toothbrush with smart timer.",
    precio: 49.95,
    stock: 6466,
  },
  {
    id: 3,
    nombre: "Lemon Garlic Marinade",
    descripcion:
      "A zesty marinade made with lemon juice and garlic, ideal for chicken or fish.",
    precio: 4.29,
    stock: 5238,
  },
  {
    id: 4,
    nombre: "Decorative Wall Tapestry",
    descripcion: "Colorful tapestry to add charm to any room.",
    precio: 34.99,
    stock: 1654,
  },
  {
    id: 5,
    nombre: "Almond Milk Yogurt",
    descripcion: "Creamy yogurt made from almond milk, vegan-friendly.",
    precio: 1.99,
    stock: 7134,
  },
  {
    id: 6,
    nombre: "Peach Fruit Cups",
    descripcion: "Juicy peach slices in light syrup, in convenient cups.",
    precio: 1.99,
    stock: 6629,
  },
  {
    id: 7,
    nombre: "Wall-Mounted Organizer",
    descripcion:
      "Practical organizer for keeping your home tidy and clutter-free.",
    precio: 34.99,
    stock: 2986,
  },
  {
    id: 8,
    nombre: "Cucumber",
    descripcion: "Fresh and crunchy cucumbers, great for salads.",
    precio: 0.99,
    stock: 6091,
  },
  {
    id: 9,
    nombre: "Chocolate Chip Muffins",
    descripcion: "Fresh baked chocolate chip muffins for breakfast.",
    precio: 3.99,
    stock: 6963,
  },
  {
    id: 10,
    nombre: "Cheese Stuffed Jalapenos",
    descripcion: "Spicy jalapenos stuffed with cheese, ideal for appetizers.",
    precio: 5.99,
    stock: 6979,
  },
  {
    id: 11,
    nombre: "LED Makeup Mirror",
    descripcion:
      "Illuminated vanity mirror with adjustable brightness settings.",
    precio: 39.99,
    stock: 1531,
  },
  {
    id: 12,
    nombre: "Pet Water Fountain with Filtration",
    descripcion:
      "Continuous stream of fresh water for pets, promoting hydration.",
    precio: 39.99,
    stock: 3184,
  },
  {
    id: 13,
    nombre: "Deep Tissue Massage Gun",
    descripcion: "Rechargeable massage gun for relieving muscle soreness.",
    precio: 89.99,
    stock: 5686,
  },
  {
    id: 14,
    nombre: "Multi-Function Meat Tenderizer",
    descripcion: "Kitchen tool for tenderizing meat to enhance flavors.",
    precio: 19.99,
    stock: 1481,
  },
  {
    id: 15,
    nombre: "Athletic Jogging Jacket",
    descripcion: "Designed for comfort and performance during workouts.",
    precio: 49.99,
    stock: 8095,
  },
  {
    id: 16,
    nombre: "Honey Graham Crackers",
    descripcion: "Sweet and crunchy honey-flavored graham crackers.",
    precio: 3.29,
    stock: 8486,
  },
  {
    id: 17,
    nombre: "Organic Coconut Flour",
    descripcion: "Finely ground flour from dried coconut meat.",
    precio: 5.49,
    stock: 7773,
  },
  {
    id: 18,
    nombre: "Maxi Wrap Dress",
    descripcion:
      "A flowy maxi dress perfect for both casual and semi-formal occasions.",
    precio: 49.99,
    stock: 8668,
  },
  {
    id: 19,
    nombre: "Vanilla Pudding Mix",
    descripcion: "Instant mix for creamy vanilla pudding.",
    precio: 1.29,
    stock: 1570,
  },
  {
    id: 20,
    nombre: "Organic Cereal Bars",
    descripcion: "Healthy snack bars packed with oats and fruit.",
    precio: 4.29,
    stock: 3823,
  },
  {
    id: 21,
    nombre: "Leather Wallet",
    descripcion: "Genuine leather wallet with multiple compartments.",
    precio: 49.99,
    stock: 9128,
  },
  {
    id: 22,
    nombre: "Wire Shelving Unit",
    descripcion: "Adjustable shelving unit for home or garage storage.",
    precio: 69.99,
    stock: 1979,
  },
  {
    id: 23,
    nombre: "Handcrafted Wooden Coasters",
    descripcion: "Set of unique wooden coasters for drinks and decor.",
    precio: 19.99,
    stock: 957,
  },
  {
    id: 24,
    nombre: "Coconut Chia Seed Pudding",
    descripcion:
      "Ready-to-eat chia seed pudding made with coconut milk, perfect for breakfast or dessert.",
    precio: 2.99,
    stock: 3126,
  },
  {
    id: 25,
    nombre: "Lightweight Workout Tank",
    descripcion: "Breathable tank top perfect for workouts or casual wear.",
    precio: 29.99,
    stock: 3449,
  },
  {
    id: 26,
    nombre: "Avocados",
    descripcion: "Fresh, creamy avocados ideal for salads and guacamole.",
    precio: 1.5,
    stock: 1097,
  },
  {
    id: 27,
    nombre: "Black Bean & Corn Salad",
    descripcion:
      "A fresh salad made with black beans, corn, and a zesty dressing, great for summer cookouts.",
    precio: 3.99,
    stock: 3509,
  },
  {
    id: 28,
    nombre: "French Bread",
    descripcion: "Freshly baked French baguette, perfect for dipping.",
    precio: 2.49,
    stock: 485,
  },
  {
    id: 29,
    nombre: "Luxury Memory Foam Mattress Topper",
    descripcion:
      "Adds extra comfort to your mattress for a better night's sleep.",
    precio: 129.99,
    stock: 5543,
  },
  {
    id: 30,
    nombre: "Reusable Food Storage Bags",
    descripcion: "Eco-friendly silicone bags for food storage and snacks.",
    precio: 19.99,
    stock: 9286,
  },
  {
    id: 31,
    nombre: "Margherita Pizza",
    descripcion:
      "A frozen pizza topped with fresh mozzarella, tomatoes, and basil.",
    precio: 7.99,
    stock: 2847,
  },
  {
    id: 32,
    nombre: "Barbecue Chicken Pizza",
    descripcion: "Pizza topped with barbecue chicken, cheese, and red onions.",
    precio: 8.99,
    stock: 8190,
  },
  {
    id: 33,
    nombre: "Teriyaki Chicken Wings",
    descripcion: "Flavorful chicken wings marinated in a sweet teriyaki glaze.",
    precio: 10.99,
    stock: 2436,
  },
  {
    id: 34,
    nombre: "Hibiscus Herbal Tea",
    descripcion: "Floral and refreshing herbal tea, great hot or iced.",
    precio: 3.29,
    stock: 1834,
  },
  {
    id: 35,
    nombre: "Sour Cream",
    descripcion: "Tangy sour cream, perfect for dips and toppings.",
    precio: 3.49,
    stock: 9990,
  },
  {
    id: 36,
    nombre: "Coconut Almond Granola",
    descripcion: "Crunchy granola made with oats, almonds, and coconut flakes.",
    precio: 4.99,
    stock: 8363,
  },
  {
    id: 37,
    nombre: "Juice Extractor",
    descripcion: "Efficient juicer for fresh fruit and vegetable juices.",
    precio: 99.99,
    stock: 8949,
  },
  {
    id: 38,
    nombre: "Garlic Parmesan Roasted Potatoes",
    descripcion:
      "Oven-roasted potatoes tossed in garlic and parmesan cheese seasoning.",
    precio: 3.99,
    stock: 7736,
  },
  {
    id: 39,
    nombre: "Pasta Maker",
    descripcion: "Manual pasta maker for homemade pasta.",
    precio: 39,
    stock: 8340,
  },
  {
    id: 40,
    nombre: "Backpack",
    descripcion: "Durable and spacious backpack for travel and school.",
    precio: 49.99,
    stock: 1938,
  },
  {
    id: 41,
    nombre: "Taro Chips",
    descripcion: "Crispy chips made from taro root, a wonderful snack.",
    precio: 3.59,
    stock: 9157,
  },
  {
    id: 42,
    nombre: "Set of Decorative Storage Bins",
    descripcion: "Colorful bins to keep your space organized.",
    precio: 34.99,
    stock: 1943,
  },
  {
    id: 43,
    nombre: "Portable Pet Stroller",
    descripcion: "Convenient stroller for pets to enjoy outdoor walks.",
    precio: 89.99,
    stock: 5242,
  },
  {
    id: 44,
    nombre: "Freestanding Wine Rack",
    descripcion: "Stylish wine rack to store and display bottles.",
    precio: 79.99,
    stock: 8517,
  },
  {
    id: 45,
    nombre: "Cinnamon Raisin Bagels",
    descripcion: "Soft bagels flavored with cinnamon and raisins.",
    precio: 4.19,
    stock: 3470,
  },
  {
    id: 46,
    nombre: "Insulated Lunch Box",
    descripcion: "Durable lunch box designed to keep food fresh and cool.",
    precio: 24.99,
    stock: 7372,
  },
  {
    id: 47,
    nombre: "Spicy Thai Noodles",
    descripcion: "Instant noodles with a spicy Thai sauce for quick meals.",
    precio: 1.99,
    stock: 8034,
  },
  {
    id: 48,
    nombre: "Window Bird Feeder",
    descripcion: "Suction cup bird feeder for close-up bird watching.",
    precio: 19.99,
    stock: 2583,
  },
  {
    id: 49,
    nombre: "Folding Pocket Knife",
    descripcion: "Compact knife with safety lock for everyday use.",
    precio: 24.99,
    stock: 1090,
  },
  {
    id: 50,
    nombre: "Mini Electric Kettle",
    descripcion: "Quick boiling kettle for small kitchens and dorms.",
    precio: 29.99,
    stock: 9178,
  },
  {
    id: 51,
    nombre: "Coconut Almond Granola",
    descripcion: "Crunchy granola made with oats, almonds, and coconut flakes.",
    precio: 4.99,
    stock: 2054,
  },
  {
    id: 52,
    nombre: "Inflatable Paddle Board",
    descripcion: "Lightweight and portable paddle board for water sports.",
    precio: 349.99,
    stock: 4442,
  },
  {
    id: 53,
    nombre: "Cat Tree",
    descripcion: "Multi-level cat tree for climbing and scratching.",
    precio: 99.99,
    stock: 3130,
  },
  {
    id: 54,
    nombre: "Gaming Mousepad",
    descripcion: "Oversized gaming mousepad with smooth surface.",
    precio: 19.99,
    stock: 9813,
  },
  {
    id: 55,
    nombre: "Almond Milk",
    descripcion: "Deliciously creamy almond milk, perfect for smoothies.",
    precio: 3.29,
    stock: 4035,
  },
  {
    id: 56,
    nombre: "Portable Pet Water Bottle",
    descripcion: "Travel-friendly water bottle for pets on the go.",
    precio: 18.99,
    stock: 941,
  },
  {
    id: 57,
    nombre: "Gardening Fairy Figurines",
    descripcion:
      "Cute fairy figurines to decorate your garden or potted plants.",
    precio: 14.99,
    stock: 9841,
  },
  {
    id: 58,
    nombre: "Beef Taco Skillet",
    descripcion:
      "A convenient meal kit for making a delicious beef taco skillet at home.",
    precio: 8.49,
    stock: 7704,
  },
  {
    id: 59,
    nombre: "Kids' Educational Tablet",
    descripcion: "Learning tablet with kid-friendly educational apps.",
    precio: 129.99,
    stock: 7089,
  },
  {
    id: 60,
    nombre: "Vegan Chickpea Salad",
    descripcion:
      "Healthy salad made with chickpeas, vegetables, and a lemon dressing.",
    precio: 3.99,
    stock: 1350,
  },
  {
    id: 61,
    nombre: "Chicken Breasts",
    descripcion: "Juicy and tender boneless chicken breasts.",
    precio: 9.99,
    stock: 5758,
  },
  {
    id: 62,
    nombre: "Granola Cereal",
    descripcion: "Crunchy granola with oats, nuts, and honey.",
    precio: 4.49,
    stock: 4692,
  },
  {
    id: 63,
    nombre: "Garden Tool Set",
    descripcion: "Complete set of gardening tools for all your needs.",
    precio: 34.99,
    stock: 3792,
  },
  {
    id: 64,
    nombre: "Suede Ankle Booties",
    descripcion: "Chic suede ankle booties, perfect for dressing up or down.",
    precio: 79.99,
    stock: 9392,
  },
  {
    id: 65,
    nombre: "Magnetic Whiteboard",
    descripcion:
      "Reusable whiteboard for notes and reminders with magnetic backing.",
    precio: 34.99,
    stock: 5924,
  },
  {
    id: 66,
    nombre: "Kale and Quinoa Salad",
    descripcion:
      "A nutritious salad with kale, quinoa, and a zesty lemon dressing.",
    precio: 6.49,
    stock: 898,
  },
  {
    id: 67,
    nombre: "Scented Soy Candles",
    descripcion: "Hand-poured candles made of natural soy wax.",
    precio: 19.99,
    stock: 1282,
  },
  {
    id: 68,
    nombre: "Pet Safety Harness",
    descripcion: "Comfortable harness designed to keep pets safe in the car.",
    precio: 24.99,
    stock: 739,
  },
  {
    id: 69,
    nombre: "Mini Pretzels",
    descripcion: "Crispy mini pretzels, a great snack any time of day.",
    precio: 2.99,
    stock: 2326,
  },
  {
    id: 70,
    nombre: "Savory Italian Herbs",
    descripcion: "A blend of dried Italian herbs for cooking.",
    precio: 2.99,
    stock: 8844,
  },
  {
    id: 71,
    nombre: "Collapsible Pet Dog Bowl",
    descripcion:
      "Travel-friendly dog bowl that is collapsible for easy storage.",
    precio: 9.99,
    stock: 5369,
  },
  {
    id: 72,
    nombre: "Pumpkin Spice Muffins",
    descripcion:
      "Moist and flavorful muffins packed with fall spices and pumpkin puree.",
    precio: 3.99,
    stock: 8740,
  },
  {
    id: 73,
    nombre: "Backpacking Tent",
    descripcion: "Lightweight and durable tent for camping trips.",
    precio: 109.99,
    stock: 6583,
  },
  {
    id: 74,
    nombre: "Mini Food Processor",
    descripcion: "Compact food processor for quick meal prep.",
    precio: 39.99,
    stock: 2919,
  },
  {
    id: 75,
    nombre: "Home Delivery Food Journal",
    descripcion: "Track your meals and nutrition with this handy food journal.",
    precio: 14.99,
    stock: 6888,
  },
  {
    id: 76,
    nombre: "Low-Fat Yogurt",
    descripcion: "Creamy yogurt with probiotics, available in various flavors.",
    precio: 3.29,
    stock: 3786,
  },
  {
    id: 77,
    nombre: "Mango Chunks",
    descripcion: "Frozen mango chunks for smoothies or snacking.",
    precio: 4.89,
    stock: 3196,
  },
  {
    id: 78,
    nombre: "Tuscan Bean Soup",
    descripcion: "A hearty mix of beans in a flavorful tomato broth.",
    precio: 2.49,
    stock: 3296,
  },
  {
    id: 79,
    nombre: "Organic Whole Wheat Flour",
    descripcion: "High-quality whole wheat flour for baking and cooking.",
    precio: 2.99,
    stock: 5697,
  },
  {
    id: 80,
    nombre: "Men's Waterproof Hiking Boots",
    descripcion: "Durable boots designed for outdoor hiking and activities.",
    precio: 89.99,
    stock: 5062,
  },
  {
    id: 81,
    nombre: "Heavy-Duty Utility Tote",
    descripcion: "Large, durable tote bag for shopping and outdoor activities.",
    precio: 34.99,
    stock: 6829,
  },
  {
    id: 82,
    nombre: "Fleece Throw Blanket",
    descripcion: "Super soft fleece blanket, perfect for coziness.",
    precio: 29.99,
    stock: 1419,
  },
  {
    id: 83,
    nombre: "Spicy Beef Taco Mix",
    descripcion: "Easy mix for making spicy beef tacos.",
    precio: 1.99,
    stock: 3646,
  },
  {
    id: 84,
    nombre: "Luxury Rolling Makeup Case",
    descripcion: "Stylish and spacious case for makeup and beauty products.",
    precio: 99.99,
    stock: 5955,
  },
  {
    id: 85,
    nombre: "Wireless Security Camera",
    descripcion: "1080p wireless security camera with night vision.",
    precio: 109.99,
    stock: 5239,
  },
  {
    id: 86,
    nombre: "Pineapple Coconut Bars",
    descripcion: "Refreshing dessert bars made with pineapple and coconut.",
    precio: 3.79,
    stock: 6709,
  },
  {
    id: 87,
    nombre: "Sweet Potato and Chickpea Bowl",
    descripcion:
      "A nourishing bowl of sweet potatoes and chickpeas with spices.",
    precio: 6.49,
    stock: 6271,
  },
  {
    id: 88,
    nombre: "Fresh Strawberries",
    descripcion: "Sweet and juicy strawberries, perfect for desserts.",
    precio: 3.99,
    stock: 6512,
  },
  {
    id: 89,
    nombre: "Teriyaki Stir-Fry Sauce",
    descripcion: "Savory teriyaki sauce for stir-frying veggies or meats.",
    precio: 3.49,
    stock: 3311,
  },
  {
    id: 90,
    nombre: "Spaghetti Squash",
    descripcion: "Low-carb vegetable for pasta alternatives.",
    precio: 3.99,
    stock: 5854,
  },
  {
    id: 91,
    nombre: "Honey Roasted Peanuts",
    descripcion: "Crunchy peanuts coated in honey, perfect for snacking.",
    precio: 3.19,
    stock: 4874,
  },
  {
    id: 92,
    nombre: "Cucumber Lime Sparkling Water",
    descripcion: "Refreshing sparkling water with cucumber and lime flavor.",
    precio: 1.49,
    stock: 868,
  },
  {
    id: 93,
    nombre: "High-Low Hem Tee",
    descripcion: "Trendy high-low tee with a relaxed fit, ideal for weekends.",
    precio: 22.99,
    stock: 5623,
  },
  {
    id: 94,
    nombre: "Thai Peanut Noodles",
    descripcion: "Noodles tossed in a spicy Thai peanut sauce.",
    precio: 4.99,
    stock: 4194,
  },
  {
    id: 95,
    nombre: "Organic Cucumber",
    descripcion: "Fresh organic cucumber perfect for salads or snacking.",
    precio: 1.29,
    stock: 5261,
  },
  {
    id: 96,
    nombre: "Vegan chocolate chip cookies",
    descripcion:
      "Delicious soft cookies, dairy-free and egg-free, perfect for treats.",
    precio: 4.79,
    stock: 8989,
  },
  {
    id: 97,
    nombre: "Potting Soil",
    descripcion: "Premium potting soil for indoor plants.",
    precio: 15.99,
    stock: 9312,
  },
  {
    id: 98,
    nombre: "Hiking Boots",
    descripcion: "Comfortable hiking boots for outdoor adventures.",
    precio: 79.99,
    stock: 1761,
  },
  {
    id: 99,
    nombre: "Coconut Oil Spray",
    descripcion: "A zero-calorie coconut oil spray for cooking and baking.",
    precio: 4.99,
    stock: 427,
  },
  {
    id: 100,
    nombre: "Essential Oils Diffuser Necklace",
    descripcion: "Wearable diffuser for scenting your space and body.",
    precio: 19.99,
    stock: 448,
  },
  {
    id: 101,
    nombre: "Stainless Steel Mixing Bowls",
    descripcion: "Set of versatile mixing bowls for cooking.",
    precio: 29.99,
    stock: 6698,
  },
  {
    id: 102,
    nombre: "Frozen Hash Browns",
    descripcion: "Shredded potatoes, perfect for breakfasts.",
    precio: 2.99,
    stock: 7146,
  },
  {
    id: 103,
    nombre: "Kids' Activity Book",
    descripcion: "Fun book filled with puzzles and games for kids.",
    precio: 14.99,
    stock: 8428,
  },
  {
    id: 104,
    nombre: "Key Finder",
    descripcion: "Bluetooth-enabled key tracker to find lost items easily.",
    precio: 19.99,
    stock: 1369,
  },
  {
    id: 105,
    nombre: "Pet Hair Remover",
    descripcion: "Effective roller for removing pet hair from furniture.",
    precio: 9.99,
    stock: 3081,
  },
  {
    id: 106,
    nombre: "Bluetooth Shower Speaker",
    descripcion: "Water-resistant Bluetooth speaker for showers.",
    precio: 24.99,
    stock: 5338,
  },
  {
    id: 107,
    nombre: "Free-Range Eggs",
    descripcion: "Fresh eggs from free-range chickens.",
    precio: 3.99,
    stock: 4247,
  },
  {
    id: 108,
    nombre: "Garlic Naan Bread",
    descripcion:
      "Soft and delicious garlic-infused flatbread, perfect for dipping.",
    precio: 3.99,
    stock: 4393,
  },
  {
    id: 109,
    nombre: "Portable Refrigerator Freezer",
    descripcion: "Compact fridge ideal for camping and road trips.",
    precio: 299.99,
    stock: 577,
  },
  {
    id: 110,
    nombre: "Digital Food Scale",
    descripcion: "Precision digital scale for accurate cooking measurements.",
    precio: 22.99,
    stock: 372,
  },
  {
    id: 111,
    nombre: "Vanilla Almond Granola",
    descripcion:
      "Crunchy granola with almonds and a hint of vanilla, perfect for breakfast.",
    precio: 4.29,
    stock: 104,
  },
  {
    id: 112,
    nombre: "Wireless Security Camera",
    descripcion: "1080p wireless security camera with night vision.",
    precio: 109.99,
    stock: 2249,
  },
];
